<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DapperPipeline\DapperPipeline.csproj" />
    <ProjectReference Include="..\..\src\DapperPipeline.SqlServer\DapperPipeline.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\DapperPipeline.Sqlite\DapperPipeline.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\DapperPipeline.PostgreSql\DapperPipeline.PostgreSql.csproj" />
  </ItemGroup>

</Project>